# -*- coding: utf-8 -*-
{
    'name': 'hospital managment',
    'version': '1.0',
    'summary': 'Hospital managment software',
    'sequence': -100,
    'description': """Odoo 14 Development Tutorials""",
    'category': 'Tutorials',
    'author': 'Odoo Mates',
    'license': 'AGPL-3',
    'maintainer': 'Odoo Mates',
    'website': 'https://www.odoomates.tech',
    'depends': ['sale','mail','purchase'],
    'data': [
        'views/patient.xml',
        'views/sale.xml',
        'views/purchase.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'security/security.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
