# -*- coding: utf-8 -*-
{
    'name': 'Shifa Customization',
    'version': '1.0',
    'summary': 'Shifa Customization software',
    'sequence': -100,
    'description': """Odoo 14 Development""",
    'category': 'Generic Modules',
    'author': 'Shifa',
    'license': 'AGPL-3',
    'maintainer': 'Shifa',
    'website': '',
    'depends': ['mail','purchase','oehealth','smartmind_shifa','sm_caregiver'],
    'data': [
        'views/purchase.xml',
        'views/physician_assessment.xml',
        'views/medical_staff.xml',
        'views/sm_contract.xml',
        'views/sh_medication_profile.xml',
        'views/sh_payment_request.xml',
        'security/security.xml',
        'data/ir_cron.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
